---
- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: restart solarplex
  ansible.builtin.systemd:
    name: solarplex
    state: restarted

- name: restart journald
  ansible.builtin.systemd:
    name: systemd-journald
    state: restarted
